IcecreamProject2/Project/Project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^icecream/', include('icecream.urls', namespace="icecream")),
    url(r'^admin/', include(admin.site.urls)),
)

IcecreamProject2/Project/icecream/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns=patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<ice_id>[0-9]+)/buy/$', views.buy, name="buy"),
)

IcecreamProject2/Project/icecream/models.py
from django.db import models

# Create your models here.

class IcecreamName(models.Model):
    cream_name=models.CharField(max_length = 100)
    cream_count=models.IntegerField(default=100)
    
    def __str__(self):
        return self.cream_name

IcecreamProject2/Project/icecream/views.py
from django.shortcuts import render

from .models import IcecreamName
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'icecream/index.html'
    context_object_name = 'latest_icecream_list'
    
    def get_queryset(self):
        return IcecreamName.objects.all().order_by('-cream_count')

class DetailView(generic.DetailView):
    model = IcecreamName
    template_name = 'icecream/detail.html'
    def get_queryset(self):
        return IcecreamName.objects.all()

class ResultsView(generic.DetailView):
    model = IcecreamName
    template_name = 'icecream/results.html'

def buy(request, ice_id):
    p = get_object_or_404(IcecreamName, pk=ice_id)
    #selected_choice = p.objects.get(pk=request.POST['cream_name'])
    if(p.cream_count==0):
        return render(request, 'icecream/detail.html', {
            'ice': p,
            'error_message': "No more scoops available",
        })
    else:
        p.cream_count -= 1
        p.save()
        return render(request, 'icecream/results.html', {
            'ice': p,
            'scoops_left': p.cream_count,
        })
        #return HttpResponseRedirect(reverse("icecream:results", args=(p.id,)))

IcecreamProject2/Project/icecream/templates/icecream/detail.html
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'icecream/style.css' %}">


<div style="margin: 10px 0 10px 0"></div>

<h1> {{ ice.cream_name }} </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="bg-info" style="padding: 10px 10px 10px 10px">
    
    <!--<a href="{% url 'icecream:buy' ice.id%}">Comfirm Buy 1 scoop</a>-->
    
    
</div>

IcecreamProject2/Project/icecream/templates/icecream/index.html
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'icecream/style.css' %}">



<div style="margin: 10px 0 10px 0"></div>

    <h1 class="text-center">Welcome to Akash's Icecream Parlour<br>
        <span class="small glyphicon glyphicon-ice-lolly-tasted"></span>
        <small>Click on a flavour to buy a scoop:</small>
        <span class="small glyphicon glyphicon-ice-lolly-tasted"></span>
    </h1>

<div class="well well-sm">
{% if latest_icecream_list %}
    <ul class="list-unstyled ">
        {% for ice in latest_icecream_list %}
            <li class="text-center">
                <a class="lead" id="flavs" href="{% url 'icecream:buy' ice.id %}">
                <span class="smalls glyphicon glyphicon-ice-lolly"></span> {{ ice.cream_name }} </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>We ran out out of stock!!</p>
{% endif %}
</div>

IcecreamProject2/Project/icecream/templates/icecream/results.html
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'icecream/style.css' %}">


<div style="margin: 10px 0 10px 0"></div>


<h1 class="bg-success" style="margin: 10px 10px 2px 10px;padding: 10px 5px 10px 10px">You just bought a scoop of {{ ice.cream_name }}</h1>
<div class="panel panel-success" style="padding: 10px 10px 10px 10px"><div class="panel-heading">
    <h1 class="panel-title" style="font-size:30px">{{ ice.cream_name }}</h1>
    </div>
    <div class="panel-body">
        <p class="lead">Scoops still in stock: {{ ice.cream_count }}</p>
    </div>
</div>